version: '3'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: always
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
    environment:
      - ZIPKIN_HOST=http://zipkin:9411
    depends_on:
      - zipkin

  weather-app:
    build:
      context: .
      dockerfile: weather-app.Dockerfile
    container_name: weather-app
    env_file:
      - .env
    ports:
      - "8081:8080"
    hostname: weather-app
    environment:
      - ZIPKIN_HOST=http://zipkin:9411
      - ZIPKIN_SERVICE_NAME=weather-service
    depends_on:
      - zipkin
  cep-app:
    depends_on:
      - weather-app
    build:
      context: .
      dockerfile: cep-app.Dockerfile
    container_name: cep-app
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_HOST=weather-app:8080
      - ZIPKIN_HOST=http://zipkin:9411
      - ZIPKIN_SERVICE_NAME=cep-service
